kind: pipeline
type: docker
name: blog-rekahsoft-ca

workspace:
  path: /drone/blog-rekahsoft-ca

steps:
- name: build-site
  image: docker.nexus.home.rekahsoft.ca/fpco/stack-build:lts-12.0
  commands:
  - ./site build
