kind: pipeline
type: docker
name: blog-rekahsoft-ca

node:
  guix: on

workspace:
  path: /drone/blog-rekahsoft-ca

steps:
- name: build
  pull: if-not-exists
  image: docker.nexus.home.rekahsoft.ca/guix:latest
  commands:
  - guix --version
  - guix time-machine -C channels.scm -- build -f guix.scm --with-source=blog-rekahsoft-ca=$(pwd)
  - ls -l /.cache/guix/
