kind: pipeline
type: docker
name: blog-rekahsoft-ca

workspace:
  path: /drone/blog-rekahsoft-ca

steps:
- name: build
  pull: if-not-exists
  image: docker.nexus.home.rekahsoft.ca/guix:latest
  commands:
  - guix --version
  - guix time-machine -C channels.scm -- build -f blog-rekahsoft-ca.scm --with-source=blog-rekahsoft-ca=$(pwd)

node:
  guix: on
